package Hash;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class StringToMd5 {

    public static void main(String[] args) {
        String s = "GeeksForGeeks";
        System.out.println("Your Hashcode Generated by MD5 is: " + getMd5(s));
    }

    public static String getMd5(String input) {
        try {

            MessageDigest digest = MessageDigest.getInstance("MD5");

            byte[] messageDigest = digest.digest(input.getBytes());

            BigInteger no = new BigInteger(1, messageDigest);

            String hashText = no.toString(16);

            while (hashText.length() < 32) {
                hashText = "0" + hashText;
            }
            return hashText;

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(StringToMd5.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }

}
